version: '3.2'

services:

  db:
    ports:
      - "27017:27017"

  todos:
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "80:8000"
    environment:
      - DEBUG=1
      - SECRET=b87704a64912103e8fb8fccde292bad2a86f253afeea7abc1987f5781c3be54e